"""Reclaimable-space detection.

Nothing in this module deletes anything. It classifies what *could* be removed
and explains why, and the caller decides. Deleting a user's files from a GUI
without them understanding the classification is the fastest way to lose
someone's trust in the tool.
"""

from __future__ import annotations

import enum
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path

from .models import FileEntry

# Leftover rubbish. Never anything a person made deliberately.
TRANSIENT_EXTENSIONS = frozenset(
    {
        "tmp", "temp", "part", "partial", "crdownload", "download", "opdownload",
        "swp", "swo", "bak", "old", "orig", "rej", "lock", "asd", "autosave",
    }
)

TRANSIENT_NAMES = frozenset(
    {
        "thumbs.db", "desktop.ini", ".ds_store", "nohup.out", "dump.sql",
        "hs_err_pid.log", "ehthumbs.db",
    }
)

# Regenerable build output. Matched on any path segment.
REGENERABLE_DIRECTORIES = frozenset(
    {
        "node_modules", "dist", "build", "out", ".next", ".nuxt", ".svelte-kit",
        "target", ".cache", "__pycache__", ".pytest_cache", ".mypy_cache",
        ".ruff_cache", "coverage", ".tox", "obj", "bin", "vendor",
    }
)

ARCHIVE_EXTENSIONS = frozenset({"zip", "tar", "gz", "tgz", "bz2", "xz", "7z", "rar", "zst"})

STALE_AFTER_DAYS = 90
LARGE_FILE_BYTES = 1024**3  # 1 GiB


class CleanupKind(enum.StrEnum):
    TRANSIENT = "transient"
    REGENERABLE = "regenerable"
    STALE = "stale"
    OVERSIZED = "oversized"


@dataclass(frozen=True, slots=True)
class CleanupCandidate:
    """A group of files offered for cleanup, with the reasoning attached."""

    id: str
    kind: CleanupKind
    label: str
    detail: str
    files: tuple[FileEntry, ...]

    @property
    def size(self) -> int:
        return sum(f.size for f in self.files)

    @property
    def count(self) -> int:
        return len(self.files)

    @property
    def confidence(self) -> str:
        """How safe this is to act on without reading it. Surfaced in the UI
        so the difference between 'obviously rubbish' and 'worth a look' is
        visible before anything is selected."""
        return {
            CleanupKind.TRANSIENT: "certain",
            CleanupKind.REGENERABLE: "safe",
            CleanupKind.STALE: "review",
            CleanupKind.OVERSIZED: "review",
        }[self.kind]


def _is_transient(entry: FileEntry) -> bool:
    lowered = entry.name.lower()
    return (
        lowered in TRANSIENT_NAMES
        or entry.extension in TRANSIENT_EXTENSIONS
        or lowered.startswith("~$")
        or lowered.endswith(".tmp")
    )


def _regenerable_root(entry: FileEntry) -> str | None:
    """First path segment that marks this file as build output."""
    for part in entry.path.parts:
        if part.lower() in REGENERABLE_DIRECTORIES:
            return part.lower()
    return None


def find_cleanup_candidates(
    files: Iterable[FileEntry],
    *,
    stale_days: int = STALE_AFTER_DAYS,
    large_bytes: int = LARGE_FILE_BYTES,
    now: datetime | None = None,
) -> tuple[CleanupCandidate, ...]:
    """Group files into cleanup candidates, largest reclaimable first."""
    reference = now or datetime.now()
    stale_cutoff = (reference - timedelta(days=stale_days)).timestamp()

    transient: list[FileEntry] = []
    regenerable: dict[str, list[FileEntry]] = {}
    stale: list[FileEntry] = []
    oversized: list[FileEntry] = []

    for entry in files:
        if _is_transient(entry):
            transient.append(entry)

        marker = _regenerable_root(entry)
        if marker:
            regenerable.setdefault(marker, []).append(entry)

        if entry.mtime < stale_cutoff:
            stale.append(entry)

        if entry.size >= large_bytes:
            oversized.append(entry)

    candidates: list[CleanupCandidate] = []

    if transient:
        candidates.append(
            CleanupCandidate(
                id="transient",
                kind=CleanupKind.TRANSIENT,
                label="Leftover temporary files",
                detail=(
                    "Partially written downloads, editor swap files and OS thumbnails. "
                    "None of these are documents."
                ),
                files=tuple(transient),
            )
        )

    for name, members in regenerable.items():
        candidates.append(
            CleanupCandidate(
                id=f"regenerable:{name}",
                kind=CleanupKind.REGENERABLE,
                label=f"{name}/",
                detail=(
                    "Build output. Regenerated by the next install or build, "
                    "so it can be rebuilt if you miss it."
                ),
                files=tuple(members),
            )
        )

    if stale:
        candidates.append(
            CleanupCandidate(
                id="stale",
                kind=CleanupKind.STALE,
                label=f"Untouched for {stale_days}+ days",
                detail="Sorted oldest first. Worth opening a few before clearing.",
                files=tuple(sorted(stale, key=lambda f: f.mtime)),
            )
        )

    if oversized:
        candidates.append(
            CleanupCandidate(
                id="oversized",
                kind=CleanupKind.OVERSIZED,
                label=f"Files over {large_bytes // 1024**3} GB",
                detail="Usually most of the space in use. Nothing is removed automatically.",
                files=tuple(sorted(oversized, key=lambda f: f.size, reverse=True)),
            )
        )

    return tuple(sorted(candidates, key=lambda c: c.size, reverse=True))


@dataclass(frozen=True, slots=True)
class StaleArchive:
    file: FileEntry
    age_days: int
    entry_count: int | None  # None: not opened, and we do not open speculatively


def find_stale_archives(
    files: Iterable[FileEntry],
    *,
    older_than_days: int = 180,
    now: datetime | None = None,
) -> tuple[StaleArchive, ...]:
    """Archives nobody has touched. Often the largest single saving available."""
    reference = now or datetime.now()
    cutoff = (reference - timedelta(days=older_than_days)).timestamp()

    found = [
        StaleArchive(
            file=entry,
            age_days=max(0, (reference - entry.modified).days),
            entry_count=None,
        )
        for entry in files
        if entry.extension in ARCHIVE_EXTENSIONS and entry.mtime < cutoff
    ]

    return tuple(sorted(found, key=lambda a: a.file.size, reverse=True))


@dataclass(frozen=True, slots=True)
class LargeFolder:
    path: Path
    count: int
    size: int


def find_largest_folders(
    files: Sequence[FileEntry],
    *,
    limit: int = 10,
) -> tuple[LargeFolder, ...]:
    """Biggest directories by total size. Often the fastest way to find where
    the space actually went."""
    buckets: dict[Path, list[FileEntry]] = {}
    for entry in files:
        buckets.setdefault(entry.parent, []).append(entry)

    folders = [
        LargeFolder(path=path, count=len(members), size=sum(f.size for f in members))
        for path, members in buckets.items()
    ]

    return tuple(sorted(folders, key=lambda f: f.size, reverse=True)[:limit])
